#!/usr/bin/env python3

import rclpy
import os
import tiago_kb.embedded_image as ei
import tiago_kb.places_xml as px
from rclpy.node import Node

class KnowledgeBaseNode(Node):
    def __init__(self):
        super().__init__('knowledge_base')
        self.declare_parameter('places_xml', 'default_value')

        # Output path for tests
        output_path = '/tmp/tiago_kb'
        try:
            os.makedirs(output_path, exist_ok=True)
        except Exception as e:
            self.get_logger().info(f'Error creating output directory: {e}')

        places_xml = self.get_parameter('places_xml').get_parameter_value().string_value

        ei.test_EmbeddedImage(output_path)
        px.test_PlacesXML(output_path, places_xml)

        # Read database with places
        #self.get_logger().info(f'Parsing file "{places_xml}"')
        #places = px.PlacesXml(places_xml)
        #places = PlacesXmlParser(places_xml).getKB()

def main(args=None):
    rclpy.init(args=args)
    knowledge_base_node = KnowledgeBaseNode()
    rclpy.spin(knowledge_base_node)
    rclpy.shutdown()

if __name__ == '__main__':
    main()
